 const shopCategories = [
  { value: "electronics", label: "Electronics" },
  { value: "computers", label: "Computers & Accessories" },
  { value: "smartphones", label: "Smartphones & Tablets" },
  { value: "clothing", label: "Clothing" },
  { value: "shoes", label: "Shoes" },
  { value: "accessories", label: "Accessories" },
  { value: "beauty-health", label: "Beauty & Health" },
  { value: "cosmetics", label: "Cosmetics & Body Care" },
  { value: "home-garden", label: "Home & Garden" },
  { value: "furniture", label: "Furniture" },
  { value: "kitchenware", label: "Kitchenware" },
  { value: "sports", label: "Sports Equipment" },
  { value: "outdoor-gear", label: "Outdoor Gear" },
  { value: "fitness", label: "Fitness & Wellness" },
  { value: "automotive", label: "Automotive" },
  { value: "tools", label: "Tools & Home Improvement" },
  { value: "books", label: "Books" },
  { value: "movies-music", label: "Movies & Music" },
  { value: "toys-games", label: "Toys & Games" },
  { value: "baby-products", label: "Baby & Maternity Products" },
  { value: "food-drink", label: "Food & Drink" },
  { value: "groceries", label: "Groceries" },
  { value: "office-supplies", label: "Office Supplies" },
  { value: "school-supplies", label: "School Supplies" },
  { value: "pet-supplies", label: "Pet Supplies" },
  { value: "pet-food", label: "Pet Food" },
  { value: "garden-outdoor", label: "Garden & Outdoor" },
  { value: "gaming", label: "Gaming & Entertainment" },
  { value: "education", label: "Education & Learning" },
  { value: "stationery", label: "Stationery & Hobby Supplies" },
  { value: "pharmacy", label: "Drugstore & Health Products" },
  { value: "beverages", label: "Beverages" },
  { value: "hardware", label: "DIY & Hardware" },
  { value: "household", label: "Household Appliances" },
  { value: "modular-storage", label: "Modular Storage & Organization" }
];

export default shopCategories