import Header from '../components/header/Header';
import './css/global.css';
import './css/euclid-circular-a-font.css';

export const metadata = {
  title: 'Welcome to user-ui-main',
  description: 'Generated by create-nx-workspace',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Header/>
      <body>{children}</body>
    </html>
  )
}
